return function(WindUI, Creator)
	return {

		-- ══════════════════════════════════════════════════════
		--  ORIGINAL WINDUI THEMES (kept intact)
		-- ══════════════════════════════════════════════════════

		Dark = {
			Name = "Dark",
			Accent = Color3.fromHex("#18181b"),
			Dialog = Color3.fromHex("#1a1a1a"),
			Outline = Color3.fromHex("#FFFFFF"),
			Text = Color3.fromHex("#FFFFFF"),
			Placeholder = Color3.fromHex("#a1a1a1"),
			Background = Color3.fromHex("#101010"),
			Button = Color3.fromHex("#52525b"),
			Icon = Color3.fromHex("#a1a1aa"),
			Toggle = Color3.fromHex("#33C759"),
			Slider = Color3.fromHex("#0091FF"),
			Checkbox = Color3.fromHex("#0091FF"),
			PanelBackground = Color3.fromHex("#FFFFFF"),
			PanelBackgroundTransparency = 0.95,
			SliderIcon = Color3.fromHex("#908F95"),
			Primary = Color3.fromHex("#0091FF"),
			LabelBackground = Color3.fromHex("#000000"),
			LabelBackgroundTransparency = 0.83,
			ElementBackground = Color3.fromHex("#2A2A2C"),
			ElementBackgroundTransparency = 0,
		},

		Light = {
			Name = "Light",
			Accent = Color3.fromHex("#efefef"),
			Dialog = Color3.fromHex("#f4f4f5"),
			Outline = Color3.fromHex("#ffffff"),
			Text = Color3.fromHex("#000000"),
			Placeholder = Color3.fromHex("#555555"),
			Background = Color3.fromHex("#FFFFFF"),
			Button = Color3.fromHex("#18181b"),
			Icon = Color3.fromHex("#52525b"),
			Toggle = Color3.fromHex("#33C759"),
			Slider = Color3.fromHex("#0091FF"),
			Checkbox = Color3.fromHex("#0091FF"),
			DropdownTabBackground = Color3.fromHex("#bebebe"),
			DropdownBackground = Color3.fromHex("#ffffff"),
			TabBackground = Color3.fromHex("#ffffff"),
			TabBackgroundHover = Color3.fromHex("#f3f3f3"),
			TabBackgroundHoverTransparency = 0,
			TabBackgroundActive = Color3.fromHex("#efefef"),
			TabBackgroundActiveTransparency = 0,
			PanelBackground = Color3.fromHex("#efefef"),
			PanelBackgroundTransparency = 0,
			LabelBackground = Color3.fromHex("#efefef"),
			LabelBackgroundTransparency = 0,
			ElementBackground = Color3.fromHex("#ffffff"),
			ElementBackgroundTransparency = 0,
		},

		Rose = {
			Name = "Rose",
			Accent = Color3.fromHex("#be185d"),
			Dialog = Color3.fromHex("#4c0519"),
			Text = Color3.fromHex("#fdf2f8"),
			Placeholder = Color3.fromHex("#d67aa6"),
			Background = Color3.fromHex("#1f0308"),
			Button = Color3.fromHex("#e95f74"),
			Icon = Color3.fromHex("#fb7185"),
			ElementBackground = Color3.fromHex("#381E23"),
			ElementBackgroundTransparency = 0,
		},

		Plant = {
			Name = "Plant",
			Accent = Color3.fromHex("#166534"),
			Dialog = Color3.fromHex("#052e16"),
			Text = Color3.fromHex("#f0fdf4"),
			Placeholder = Color3.fromHex("#4fbf7a"),
			Background = Color3.fromHex("#0a1b0f"),
			Button = Color3.fromHex("#16a34a"),
			Icon = Color3.fromHex("#4ade80"),
			ElementBackground = Color3.fromHex("#28342A"),
			ElementBackgroundTransparency = 0,
		},

		Red = {
			Name = "Red",
			Accent = Color3.fromHex("#991b1b"),
			Dialog = Color3.fromHex("#450a0a"),
			Text = Color3.fromHex("#fef2f2"),
			Placeholder = Color3.fromHex("#d95353"),
			Background = Color3.fromHex("#1c0606"),
			Button = Color3.fromHex("#dc2626"),
			Icon = Color3.fromHex("#ef4444"),
			ElementBackground = Color3.fromHex("#322221"),
			ElementBackgroundTransparency = 0,
		},

		Indigo = {
			Name = "Indigo",
			Accent = Color3.fromHex("#3730a3"),
			Dialog = Color3.fromHex("#1e1b4b"),
			Text = Color3.fromHex("#f1f5f9"),
			Placeholder = Color3.fromHex("#7078d9"),
			Background = Color3.fromHex("#0f0a2e"),
			Button = Color3.fromHex("#4f46e5"),
			Icon = Color3.fromHex("#6366f1"),
			ElementBackground = Color3.fromHex("#282543"),
			ElementBackgroundTransparency = 0,
		},

		Sky = {
			Name = "Sky",
			Accent = Color3.fromHex("#00d4ff"),
			Dialog = Color3.fromHex("#0a4d66"),
			Text = Color3.fromHex("#e6f7ff"),
			Placeholder = Color3.fromHex("#66b3cc"),
			Background = Color3.fromHex("#051a26"),
			Button = Color3.fromHex("#00a8cc"),
			Icon = Color3.fromHex("#2db8d9"),
			Toggle = Color3.fromHex("#00d9d9"),
			Slider = Color3.fromHex("#00d4ff"),
			Checkbox = Color3.fromHex("#00d4ff"),
			PanelBackground = Color3.fromHex("#0d3a47"),
			PanelBackgroundTransparency = 0.8,
			ElementBackground = Color3.fromHex("#172E3B"),
			ElementBackgroundTransparency = 0,
		},

		Violet = {
			Name = "Violet",
			Accent = Color3.fromHex("#6d28d9"),
			Dialog = Color3.fromHex("#3c1361"),
			Text = Color3.fromHex("#faf5ff"),
			Placeholder = Color3.fromHex("#8f7ee0"),
			Background = Color3.fromHex("#1e0a3e"),
			Button = Color3.fromHex("#7c3aed"),
			Icon = Color3.fromHex("#8b5cf6"),
			ElementBackground = Color3.fromHex("#342650"),
			ElementBackgroundTransparency = 0,
		},

		Amber = {
			Name = "Amber",
			Accent = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#b45309"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#d97706"), Transparency = 0 } }, { Rotation = 45 }),
			Dialog = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#451a03"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#6b2e05"), Transparency = 0 } }, { Rotation = 90 }),
			Text = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#fffbeb"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#fff7ed"), Transparency = 0 } }, { Rotation = 45 }),
			Placeholder = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#d1a326"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#fbbf24"), Transparency = 0 } }, { Rotation = 45 }),
			Background = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#1c1003"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#3f210d"), Transparency = 0 } }, { Rotation = 90 }),
			Button = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#d97706"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#f59e0b"), Transparency = 0 } }, { Rotation = 45 }),
			Icon = Color3.fromHex("#f59e0b"),
			Toggle = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#d97706"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#f59e0b"), Transparency = 0 } }, { Rotation = 45 }),
			Slider = Color3.fromHex("#d97706"),
			Checkbox = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#d97706"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#fbbf24"), Transparency = 0 } }, { Rotation = 45 }),
			PanelBackground = Color3.fromHex("#FFFFFF"),
			PanelBackgroundTransparency = 0.95,
			ElementBackground = Color3.fromHex("#3A2E22"),
			ElementBackgroundTransparency = 0,
		},

		Emerald = {
			Name = "Emerald",
			Accent = Color3.fromHex("#047857"),
			Dialog = Color3.fromHex("#022c22"),
			Text = Color3.fromHex("#ecfdf5"),
			Placeholder = Color3.fromHex("#3fbf8f"),
			Background = Color3.fromHex("#011411"),
			Button = Color3.fromHex("#059669"),
			Icon = Color3.fromHex("#10b981"),
			ElementBackground = Color3.fromHex("#202E2A"),
			ElementBackgroundTransparency = 0,
		},

		Midnight = {
			Name = "Midnight",
			Accent = Color3.fromHex("#1e3a8a"),
			Dialog = Color3.fromHex("#0c1e42"),
			Text = Color3.fromHex("#dbeafe"),
			Placeholder = Color3.fromHex("#2f74d1"),
			Background = Color3.fromHex("#0a0f1e"),
			Button = Color3.fromHex("#2563eb"),
			Primary = Color3.fromHex("#2563eb"),
			Icon = Color3.fromHex("#5591f4"),
			ElementBackground = Color3.fromHex("#242836"),
			ElementBackgroundTransparency = 0,
		},

		Crimson = {
			Name = "Crimson",
			Accent = Color3.fromHex("#b91c1c"),
			Dialog = Color3.fromHex("#450a0a"),
			Text = Color3.fromHex("#fef2f2"),
			Placeholder = Color3.fromHex("#6f757b"),
			Background = Color3.fromHex("#0c0404"),
			Button = Color3.fromHex("#991b1b"),
			Icon = Color3.fromHex("#dc2626"),
			ElementBackground = Color3.fromHex("#251F1F"),
			ElementBackgroundTransparency = 0,
		},

		MonokaiPro = {
			Name = "Monokai Pro",
			Accent = Color3.fromHex("#fc9867"),
			Dialog = Color3.fromHex("#1e1e1e"),
			Text = Color3.fromHex("#fcfcfa"),
			Placeholder = Color3.fromHex("#afafaf"),
			Background = Color3.fromHex("#191622"),
			Button = Color3.fromHex("#ab9df2"),
			Icon = Color3.fromHex("#a9dc76"),
			ElementBackground = Color3.fromHex("#323039"),
			ElementBackgroundTransparency = 0,
			Metadata = { PullRequest = 23 },
		},

		CottonCandy = {
			Name = "Cotton Candy",
			Accent = Color3.fromHex("#ec4899"),
			Dialog = Color3.fromHex("#2d1b3d"),
			Text = Color3.fromHex("#fdf2f8"),
			Placeholder = Color3.fromHex("#8a5fd3"),
			Background = Color3.fromHex("#1a0b2e"),
			Button = Color3.fromHex("#d946ef"),
			Slider = Color3.fromHex("#d946ef"),
			Icon = Color3.fromHex("#06b6d4"),
			ElementBackground = Color3.fromHex("#312643"),
			ElementBackgroundTransparency = 0,
		},

		Mellowsi = {
			Name = "Mellowsi",
			Accent = Color3.fromHex("#342A1E"),
			Dialog = Color3.fromHex("#291C13"),
			Text = Color3.fromHex("#F5EBDD"),
			Placeholder = Color3.fromHex("#9C8A73"),
			Background = Color3.fromHex("#1C1002"),
			Button = Color3.fromHex("#342A1E"),
			Icon = Color3.fromHex("#C9B79C"),
			Toggle = Color3.fromHex("#a9873f"),
			Slider = Color3.fromHex("#C9A24D"),
			Checkbox = Color3.fromHex("#C9A24D"),
			ElementBackground = Color3.fromHex("#33291E"),
			ElementBackgroundTransparency = 0,
			Metadata = { PullRequest = 52 },
		},

		Rainbow = {
			Name = "Rainbow",
			Accent = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#00ff41"), Transparency = 0 }, ["33"] = { Color = Color3.fromHex("#00ffff"), Transparency = 0 }, ["66"] = { Color = Color3.fromHex("#0080ff"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#8000ff"), Transparency = 0 } }, { Rotation = 45 }),
			Dialog = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#ff0080"), Transparency = 0 }, ["25"] = { Color = Color3.fromHex("#8000ff"), Transparency = 0 }, ["50"] = { Color = Color3.fromHex("#0080ff"), Transparency = 0 }, ["75"] = { Color = Color3.fromHex("#00ff80"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#ff8000"), Transparency = 0 } }, { Rotation = 135 }),
			Text = Color3.fromHex("#ffffff"),
			Placeholder = Color3.fromHex("#00ff80"),
			Background = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#ff0040"), Transparency = 0 }, ["20"] = { Color = Color3.fromHex("#ff4000"), Transparency = 0 }, ["40"] = { Color = Color3.fromHex("#ffff00"), Transparency = 0 }, ["60"] = { Color = Color3.fromHex("#00ff40"), Transparency = 0 }, ["80"] = { Color = Color3.fromHex("#0040ff"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#4000ff"), Transparency = 0 } }, { Rotation = 90 }),
			Button = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#ff0080"), Transparency = 0 }, ["25"] = { Color = Color3.fromHex("#ff8000"), Transparency = 0 }, ["50"] = { Color = Color3.fromHex("#ffff00"), Transparency = 0 }, ["75"] = { Color = Color3.fromHex("#80ff00"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#00ffff"), Transparency = 0 } }, { Rotation = 60 }),
			Icon = Color3.fromHex("#ffffff"),
		},

		-- ══════════════════════════════════════════════════════
		--  LEVIATHAN EXCLUSIVE THEMES
		-- ══════════════════════════════════════════════════════

		-- Deep oceanic blue-teal
		Ocean = {
			Name = "Ocean",
			Accent = Color3.fromHex("#0f4c75"),
			Dialog = Color3.fromHex("#0a2a42"),
			Text = Color3.fromHex("#e8f4fd"),
			Placeholder = Color3.fromHex("#5ba3c9"),
			Background = Color3.fromHex("#050e1a"),
			Button = Color3.fromHex("#1b6ca8"),
			Icon = Color3.fromHex("#48c0e0"),
			Toggle = Color3.fromHex("#00d4aa"),
			Slider = Color3.fromHex("#1b6ca8"),
			Checkbox = Color3.fromHex("#1b6ca8"),
			ElementBackground = Color3.fromHex("#112236"),
			ElementBackgroundTransparency = 0,
		},

		-- Discord-inspired blurple
		Blurple = {
			Name = "Blurple",
			Accent = Color3.fromHex("#5865F2"),
			Dialog = Color3.fromHex("#2b2d31"),
			Text = Color3.fromHex("#FFFFFF"),
			Placeholder = Color3.fromHex("#949BA4"),
			Background = Color3.fromHex("#1e1f22"),
			Button = Color3.fromHex("#5865F2"),
			Icon = Color3.fromHex("#b5bac1"),
			Toggle = Color3.fromHex("#23A55A"),
			Slider = Color3.fromHex("#5865F2"),
			Checkbox = Color3.fromHex("#5865F2"),
			Primary = Color3.fromHex("#5865F2"),
			PanelBackground = Color3.fromHex("#2b2d31"),
			PanelBackgroundTransparency = 0,
			LabelBackground = Color3.fromHex("#313338"),
			LabelBackgroundTransparency = 0,
			ElementBackground = Color3.fromHex("#313338"),
			ElementBackgroundTransparency = 0,
		},

		-- Neon green hacker aesthetic
		Matrix = {
			Name = "Matrix",
			Accent = Color3.fromHex("#003300"),
			Dialog = Color3.fromHex("#001100"),
			Text = Color3.fromHex("#00FF41"),
			Placeholder = Color3.fromHex("#007722"),
			Background = Color3.fromHex("#000800"),
			Button = Color3.fromHex("#003300"),
			Icon = Color3.fromHex("#00CC33"),
			Toggle = Color3.fromHex("#00FF41"),
			Slider = Color3.fromHex("#00CC33"),
			Checkbox = Color3.fromHex("#00CC33"),
			ElementBackground = Color3.fromHex("#001A00"),
			ElementBackgroundTransparency = 0,
		},

		-- Apple macOS-style frosted glass light
		Frost = {
			Name = "Frost",
			Accent = Color3.fromHex("#f0f0f5"),
			Dialog = Color3.fromHex("#e8e8f0"),
			Text = Color3.fromHex("#1c1c1e"),
			Placeholder = Color3.fromHex("#8e8e93"),
			Background = Color3.fromHex("#f5f5f7"),
			Button = Color3.fromHex("#007AFF"),
			Icon = Color3.fromHex("#636366"),
			Toggle = Color3.fromHex("#34C759"),
			Slider = Color3.fromHex("#007AFF"),
			Checkbox = Color3.fromHex("#007AFF"),
			Primary = Color3.fromHex("#007AFF"),
			PanelBackground = Color3.fromHex("#ffffff"),
			PanelBackgroundTransparency = 0,
			LabelBackground = Color3.fromHex("#f2f2f7"),
			LabelBackgroundTransparency = 0,
			ElementBackground = Color3.fromHex("#ffffff"),
			ElementBackgroundTransparency = 0,
			TabBackground = Color3.fromHex("#ffffff"),
			TabBackgroundHover = Color3.fromHex("#f2f2f7"),
			TabBackgroundHoverTransparency = 0,
			TabBackgroundActive = Color3.fromHex("#e5e5ea"),
			TabBackgroundActiveTransparency = 0,
		},

		-- Deep red/black vampire aesthetic
		Vampire = {
			Name = "Vampire",
			Accent = Color3.fromHex("#6b0000"),
			Dialog = Color3.fromHex("#2a0000"),
			Text = Color3.fromHex("#f8e8e8"),
			Placeholder = Color3.fromHex("#994444"),
			Background = Color3.fromHex("#110000"),
			Button = Color3.fromHex("#8b0000"),
			Icon = Color3.fromHex("#cc2222"),
			Toggle = Color3.fromHex("#cc0000"),
			Slider = Color3.fromHex("#990000"),
			Checkbox = Color3.fromHex("#990000"),
			ElementBackground = Color3.fromHex("#220000"),
			ElementBackgroundTransparency = 0,
		},

		-- Warm sandy desert
		Sand = {
			Name = "Sand",
			Accent = Color3.fromHex("#92703b"),
			Dialog = Color3.fromHex("#4a3520"),
			Text = Color3.fromHex("#fdf6e3"),
			Placeholder = Color3.fromHex("#b8966e"),
			Background = Color3.fromHex("#1a1208"),
			Button = Color3.fromHex("#c4924e"),
			Icon = Color3.fromHex("#d4a96a"),
			Toggle = Color3.fromHex("#c4924e"),
			Slider = Color3.fromHex("#c4924e"),
			Checkbox = Color3.fromHex("#c4924e"),
			ElementBackground = Color3.fromHex("#2e2010"),
			ElementBackgroundTransparency = 0,
		},

		-- Cyberpunk neon pink/cyan
		Cyberpunk = {
			Name = "Cyberpunk",
			Accent = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#ff00aa"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#00ffee"), Transparency = 0 } }, { Rotation = 45 }),
			Dialog = Color3.fromHex("#0d0d1a"),
			Text = Color3.fromHex("#f0f0ff"),
			Placeholder = Color3.fromHex("#8888bb"),
			Background = Color3.fromHex("#050510"),
			Button = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#cc0088"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#00cccc"), Transparency = 0 } }, { Rotation = 45 }),
			Icon = Color3.fromHex("#ff44cc"),
			Toggle = Color3.fromHex("#00ffee"),
			Slider = Color3.fromHex("#ff00aa"),
			Checkbox = Color3.fromHex("#00ffee"),
			Primary = Color3.fromHex("#ff00aa"),
			ElementBackground = Color3.fromHex("#0d0d22"),
			ElementBackgroundTransparency = 0,
		},

		-- Flat clean pastel
		Pastel = {
			Name = "Pastel",
			Accent = Color3.fromHex("#c9b8e8"),
			Dialog = Color3.fromHex("#e8daf5"),
			Text = Color3.fromHex("#3d2b5e"),
			Placeholder = Color3.fromHex("#9980bb"),
			Background = Color3.fromHex("#f5eeff"),
			Button = Color3.fromHex("#b39ddb"),
			Icon = Color3.fromHex("#9575cd"),
			Toggle = Color3.fromHex("#81c784"),
			Slider = Color3.fromHex("#b39ddb"),
			Checkbox = Color3.fromHex("#b39ddb"),
			PanelBackground = Color3.fromHex("#ede7f6"),
			PanelBackgroundTransparency = 0,
			LabelBackground = Color3.fromHex("#e8daf5"),
			LabelBackgroundTransparency = 0,
			ElementBackground = Color3.fromHex("#ede7f6"),
			ElementBackgroundTransparency = 0,
			TabBackground = Color3.fromHex("#e8daf5"),
			TabBackgroundHover = Color3.fromHex("#ddd0f0"),
			TabBackgroundHoverTransparency = 0,
			TabBackgroundActive = Color3.fromHex("#d0bfec"),
			TabBackgroundActiveTransparency = 0,
		},

		-- Pure black OLED
		Abyss = {
			Name = "Abyss",
			Accent = Color3.fromHex("#000000"),
			Dialog = Color3.fromHex("#0a0a0a"),
			Outline = Color3.fromHex("#222222"),
			Text = Color3.fromHex("#e8e8e8"),
			Placeholder = Color3.fromHex("#555555"),
			Background = Color3.fromHex("#000000"),
			Button = Color3.fromHex("#1a1a1a"),
			Icon = Color3.fromHex("#666666"),
			Toggle = Color3.fromHex("#448844"),
			Slider = Color3.fromHex("#446688"),
			Checkbox = Color3.fromHex("#446688"),
			PanelBackground = Color3.fromHex("#111111"),
			PanelBackgroundTransparency = 0,
			LabelBackground = Color3.fromHex("#000000"),
			LabelBackgroundTransparency = 0.7,
			ElementBackground = Color3.fromHex("#111111"),
			ElementBackgroundTransparency = 0,
		},

		-- Slate / Fluent-inspired neutral
		Slate = {
			Name = "Slate",
			Accent = Color3.fromHex("#334155"),
			Dialog = Color3.fromHex("#1e293b"),
			Text = Color3.fromHex("#f1f5f9"),
			Placeholder = Color3.fromHex("#94a3b8"),
			Background = Color3.fromHex("#0f172a"),
			Button = Color3.fromHex("#475569"),
			Icon = Color3.fromHex("#94a3b8"),
			Toggle = Color3.fromHex("#38bdf8"),
			Slider = Color3.fromHex("#38bdf8"),
			Checkbox = Color3.fromHex("#38bdf8"),
			Primary = Color3.fromHex("#38bdf8"),
			ElementBackground = Color3.fromHex("#1e293b"),
			ElementBackgroundTransparency = 0,
		},

		-- Orange/warm developer
		Sunset = {
			Name = "Sunset",
			Accent = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#c2410c"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#db2777"), Transparency = 0 } }, { Rotation = 45 }),
			Dialog = Color3.fromHex("#2d1010"),
			Text = Color3.fromHex("#fff7ed"),
			Placeholder = Color3.fromHex("#c87050"),
			Background = Color3.fromHex("#180808"),
			Button = WindUI:Gradient({ ["0"] = { Color = Color3.fromHex("#ea580c"), Transparency = 0 }, ["100"] = { Color = Color3.fromHex("#ec4899"), Transparency = 0 } }, { Rotation = 45 }),
			Icon = Color3.fromHex("#fb923c"),
			Toggle = Color3.fromHex("#f97316"),
			Slider = Color3.fromHex("#ea580c"),
			Checkbox = Color3.fromHex("#f97316"),
			ElementBackground = Color3.fromHex("#2a1510"),
			ElementBackgroundTransparency = 0,
		},

		-- Nordic/Scandinavian cool grey-blue
		Nord = {
			Name = "Nord",
			Accent = Color3.fromHex("#3b4252"),
			Dialog = Color3.fromHex("#2e3440"),
			Text = Color3.fromHex("#eceff4"),
			Placeholder = Color3.fromHex("#7a8499"),
			Background = Color3.fromHex("#242933"),
			Button = Color3.fromHex("#5e81ac"),
			Icon = Color3.fromHex("#88c0d0"),
			Toggle = Color3.fromHex("#a3be8c"),
			Slider = Color3.fromHex("#5e81ac"),
			Checkbox = Color3.fromHex("#81a1c1"),
			Primary = Color3.fromHex("#81a1c1"),
			PanelBackground = Color3.fromHex("#3b4252"),
			PanelBackgroundTransparency = 0,
			LabelBackground = Color3.fromHex("#3b4252"),
			LabelBackgroundTransparency = 0,
			ElementBackground = Color3.fromHex("#3b4252"),
			ElementBackgroundTransparency = 0,
		},

		-- Dracula color scheme
		Dracula = {
			Name = "Dracula",
			Accent = Color3.fromHex("#44475a"),
			Dialog = Color3.fromHex("#282a36"),
			Text = Color3.fromHex("#f8f8f2"),
			Placeholder = Color3.fromHex("#6272a4"),
			Background = Color3.fromHex("#1e1f29"),
			Button = Color3.fromHex("#bd93f9"),
			Icon = Color3.fromHex("#ff79c6"),
			Toggle = Color3.fromHex("#50fa7b"),
			Slider = Color3.fromHex("#bd93f9"),
			Checkbox = Color3.fromHex("#bd93f9"),
			Primary = Color3.fromHex("#bd93f9"),
			ElementBackground = Color3.fromHex("#44475a"),
			ElementBackgroundTransparency = 0,
		},

		-- Solarized dark
		Solarized = {
			Name = "Solarized",
			Accent = Color3.fromHex("#073642"),
			Dialog = Color3.fromHex("#002b36"),
			Text = Color3.fromHex("#fdf6e3"),
			Placeholder = Color3.fromHex("#657b83"),
			Background = Color3.fromHex("#001f27"),
			Button = Color3.fromHex("#268bd2"),
			Icon = Color3.fromHex("#2aa198"),
			Toggle = Color3.fromHex("#859900"),
			Slider = Color3.fromHex("#268bd2"),
			Checkbox = Color3.fromHex("#268bd2"),
			Primary = Color3.fromHex("#268bd2"),
			ElementBackground = Color3.fromHex("#073642"),
			ElementBackgroundTransparency = 0,
		},

		-- Tokyonight
		TokyoNight = {
			Name = "Tokyo Night",
			Accent = Color3.fromHex("#1a1b2e"),
			Dialog = Color3.fromHex("#16161e"),
			Text = Color3.fromHex("#c0caf5"),
			Placeholder = Color3.fromHex("#565f89"),
			Background = Color3.fromHex("#0d0e17"),
			Button = Color3.fromHex("#7aa2f7"),
			Icon = Color3.fromHex("#bb9af7"),
			Toggle = Color3.fromHex("#9ece6a"),
			Slider = Color3.fromHex("#7aa2f7"),
			Checkbox = Color3.fromHex("#7aa2f7"),
			Primary = Color3.fromHex("#7aa2f7"),
			PanelBackground = Color3.fromHex("#24283b"),
			PanelBackgroundTransparency = 0,
			ElementBackground = Color3.fromHex("#1f2335"),
			ElementBackgroundTransparency = 0,
		},

		-- Catppuccin Mocha
		Catppuccin = {
			Name = "Catppuccin",
			Accent = Color3.fromHex("#313244"),
			Dialog = Color3.fromHex("#1e1e2e"),
			Text = Color3.fromHex("#cdd6f4"),
			Placeholder = Color3.fromHex("#6c7086"),
			Background = Color3.fromHex("#11111b"),
			Button = Color3.fromHex("#cba6f7"),
			Icon = Color3.fromHex("#89b4fa"),
			Toggle = Color3.fromHex("#a6e3a1"),
			Slider = Color3.fromHex("#cba6f7"),
			Checkbox = Color3.fromHex("#cba6f7"),
			Primary = Color3.fromHex("#cba6f7"),
			PanelBackground = Color3.fromHex("#313244"),
			PanelBackgroundTransparency = 0,
			ElementBackground = Color3.fromHex("#313244"),
			ElementBackgroundTransparency = 0,
		},

		-- One Dark (Atom)
		OneDark = {
			Name = "One Dark",
			Accent = Color3.fromHex("#21252b"),
			Dialog = Color3.fromHex("#1d2026"),
			Text = Color3.fromHex("#abb2bf"),
			Placeholder = Color3.fromHex("#5c6370"),
			Background = Color3.fromHex("#181a1f"),
			Button = Color3.fromHex("#61afef"),
			Icon = Color3.fromHex("#c678dd"),
			Toggle = Color3.fromHex("#98c379"),
			Slider = Color3.fromHex("#61afef"),
			Checkbox = Color3.fromHex("#61afef"),
			Primary = Color3.fromHex("#61afef"),
			ElementBackground = Color3.fromHex("#2c313a"),
			ElementBackgroundTransparency = 0,
		},

	}
end
